{
 "title": "Klaytn-EN",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "server", "query": { "query": "label_values(instance)" } },
   {
    "name": "MaxFds",
    "query": {
     "query": "query_result(process_max_fds{instance=\"$server\"})"
    }
   }
  ]
 },
 "panels": [
  { "title": "BlockChain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TPS (rate)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(klaytn_blockchain_block_tx_counter{instance=\"$server\"}[30s])"
    }
   ]
  },
  {
   "title": "BlockInsertTime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klaytn_chain_inserts{instance=\"$server\"}"
    }
   ]
  },
  {
   "title": "Consensus Round Time",
   "type": "stat",
   "description": "Consensus Round Time (prepare -> commit)",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klaytn_consensus_istanbul_core_timer{instance=\"$server\"}"
    }
   ]
  },
  {
   "title": "Head Block Number",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klaytn_blockchain_head_blocknumber{instance=\"$server\"}"
    }
   ]
  },
  {
   "title": "Live Peer Con",
   "type": "stat",
   "description": "Live Peer Connection",
   "gridPos": { "h": 5, "w": 2, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klaytn_p2p_PeerCountGauge{instance=\"$server\"}"
    }
   ]
  },
  {
   "title": "TxPool (pending)",
   "type": "stat",
   "description": "TxPool Pending Current Size",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " klaytn_tx_pool_pending_gauge{instance=\"$server\"}"
    }
   ]
  },
  {
   "title": "TxPool (queue)",
   "type": "stat",
   "description": "TxPool Queue Current Size",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " klaytn_tx_pool_queue_gauge{instance=\"$server\"}"
    }
   ]
  },
  {
   "title": "Tx Received Count",
   "type": "stat",
   "description": "Tx Received Count",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klaytn_klay_prop_txns_in_packets{instance=\"$server\"}"
    }
   ]
  },
  {
   "title": "Tx Received Bytes",
   "type": "stat",
   "description": "Tx Received Bytes",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klaytn_klay_prop_txns_in_traffic{instance=\"$server\"}"
    }
   ]
  },
  {
   "title": "Tx Send Count",
   "type": "stat",
   "description": "Tx Send Count",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klaytn_klay_prop_txns_out_packets{instance=\"$server\"}"
    }
   ]
  },
  {
   "title": "Tx Send Bytes",
   "type": "stat",
   "description": "Tx Send Bytes",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klaytn_klay_prop_txns_out_traffic{instance=\"$server\"}"
    }
   ]
  },
  { "title": "Process Infos", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }, "repeat": "server" },
  {
   "title": "CPU (rate)",
   "type": "stat",
   "description": "process cpu consume time rate (per second)",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"$server\"}[30s])"
    }
   ]
  },
  {
   "title": "Mem(res)",
   "type": "stat",
   "description": "Memory Allocation (resident)",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"$server\"}"
    }
   ]
  },
  {
   "title": "Mem(vir)",
   "type": "stat",
   "description": "Memory Allocation (virtual)",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{instance=\"$server\"}"
    }
   ]
  },
  {
   "title": "Opened fd",
   "type": "stat",
   "description": "Opened File Description",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_open_fds{instance=\"$server\"}"
    }
   ]
  },
  { "title": "All", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "TPS (rate)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(klaytn_blockchain_block_tx_counter[30s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TxPool (queue)",
   "type": "graph",
   "description": "txpool queue current size",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "klaytn_tx_pool_queue_gauge", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Head Block Num",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_blockchain_head_blocknumber",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Block Produce(rate)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(klaytn_blockchain_head_blocknumber[30s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TxPool - pending",
   "type": "graph",
   "description": "txpool pending current size",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "klaytn_tx_pool_pending_gauge", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "BlockCount (Received)",
   "type": "graph",
   "description": "Recived Block Count",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_prop_blocks_in_packets",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "BlockCount(Send)",
   "type": "graph",
   "description": "Send Block Count",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_prop_blocks_out_packets",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "BlockInsertTime(sec)",
   "type": "graph",
   "description": "BlockInsertTime(sec)",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "sec" }
   ],
   "targets": [
    { "expr": "klaytn_chain_inserts", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Live Peer Con",
   "type": "graph",
   "description": "Live Peer Connection",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "klaytn_p2p_PeerCountGauge", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "P2P Live Connection",
   "type": "graph",
   "description": "P2P Live Connection",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_p2p_ConnectionCountGauge",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "P2P Inbound Connection",
   "type": "graph",
   "description": "P2P Inbound Connection",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_p2p_ConnectionInCountGauge",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Consensus Commit Sec",
   "type": "graph",
   "description": "Consensus Commit Sec",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 31 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "klaytn_consensus_istanbul_core_timer",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "BlockBytes (Received)",
   "type": "graph",
   "description": "BlockBytes (Received)",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_prop_blocks_in_traffic",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "BlockBytes (Send)",
   "type": "graph",
   "description": "BlockBytes (Send)",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 38 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_prop_blocks_out_traffic",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "tx received bytes",
   "type": "graph",
   "description": "tx received bytes",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_prop_txns_in_packets",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "P2P Outbound Connection",
   "type": "graph",
   "description": "P2P Outbound Connection",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_p2p_ConnectionOutCountGauge",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU (rate, sec)",
   "type": "graph",
   "description": "cpu process consume sec (rate)",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[30s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Mem(res) - all",
   "type": "graph",
   "description": "Memory Allocation (resident)",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 45 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Mem(vir) - all",
   "type": "graph",
   "description": "Memory Allocation (virtual)",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "process_virtual_memory_bytes", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "tx send bytes",
   "type": "graph",
   "description": "tx send bytes",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 45 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_prop_txns_out_packets",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "P2P Dial Try Rate",
   "type": "graph",
   "description": "P2P Dial Try Rate",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(klaytn_p2p_DialTryCounter[30s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "P2P Dial Fail Rate",
   "type": "graph",
   "description": "P2P Dial Fail Rate",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(klaytn_p2p_DialFailCounter[30s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "LevelDB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "LevelDB (read)",
   "type": "graph",
   "description": "LevelDB (read)",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_db_chaindata_disk_read",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "LevelDB (Write)",
   "type": "graph",
   "description": "LevelDB (Write)",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 60 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_db_chaindata_disk_write",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "LevelDB 'header' dir. (R/W)",
   "type": "graph",
   "description": "LevelDB 'header' (Read/Write)",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_db_chaindata_header_disk_read",
     "legendFormat": "{{instance}}:read"
    },
    {
     "expr": "klaytn_klay_db_chaindata_header_disk_write",
     "legendFormat": "{{instance}}:write"
    }
   ]
  },
  {
   "title": "LevelDB 'body' dir. (R/W)",
   "type": "graph",
   "description": "LevelDB 'body' (Read/Write)",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 60 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_db_chaindata_body_disk_read",
     "legendFormat": "{{instance}}:read"
    },
    {
     "expr": "klaytn_klay_db_chaindata_body_disk_write",
     "legendFormat": "{{instance}}:write"
    }
   ]
  },
  {
   "title": "LevelDB 'statetrie' dir. (R/W)",
   "type": "graph",
   "description": "LevelDB 'statetrie' directory (Read/Write)",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_disk_read",
     "legendFormat": "{{instance}}:read"
    },
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_disk_write",
     "legendFormat": "{{instance}}:write"
    }
   ]
  },
  {
   "title": "LevelDB 'misc' dir. (R/W)",
   "type": "graph",
   "description": "LevelDB 'misc' directory (Read/Write)",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 67 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_db_chaindata_misc_disk_read",
     "legendFormat": "{{instance}}:read"
    },
    {
     "expr": "klaytn_klay_db_chaindata_misc_disk_write",
     "legendFormat": "{{instance}}:write"
    }
   ]
  },
  {
   "title": "LevelDB 'txlookup' dir. (R/W)",
   "type": "graph",
   "description": "LevelDB 'statetrie' directory (Read/Write)",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_db_chaindata_txlookup_disk_read",
     "legendFormat": "{{instance}}:read"
    },
    {
     "expr": "klaytn_klay_db_chaindata_txlookup_disk_write",
     "legendFormat": "{{instance}}:write"
    }
   ]
  },
  {
   "title": "LevelDB 'receipts' dir. (R/W)",
   "type": "graph",
   "description": "LevelDB 'receipts' directory (Read/Write)",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 67 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_db_chaindata_receipts_disk_read",
     "legendFormat": "{{instance}}:read"
    },
    {
     "expr": "klaytn_klay_db_chaindata_receipts_disk_write",
     "legendFormat": "{{instance}}:write"
    }
   ]
  }
 ]
}